server:
  port: 8080 # 내장 톰캣 포트번호

spring:
  profiles:
    active: default

  # MySQL Database 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/realdb?allowPublicKeyRetrieval=true&useSSL=false&requireSSL=false&rewriteBatchedStatements=true # MySQL DB 연결 주소
    username: myuser                          # MySQL DB 접속 ID
    password: mypassword                      # MySQL DB 접속 PW

  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379

    # page 설정
    web:
      pageable:
        default-page-size: 20
        max-page-size: 2000

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update  # DB 초기화 전략 (none, create, create-drop, update, validate)
    open-in-view: false  # Disable open-in-view to avoid performance issues
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL 방언으로 변경
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력

  # Cache 설정
  cache:
    type: redis

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-ids:
        success: PAYMENT_GROUP
    topic:
      payment-success: PAYMENT_SUCCESS

logging:
  level:
    org:
      apache:
        kafka: INFO
      springframework: INFO