server:
  port: 8080 # 내장 톰캣 포트번호

spring:
  profiles:
    active: default

  # MySQL Database 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/realdb?allowPublicKeyRetrieval=true&useSSL=false&requireSSL=false # MySQL DB 연결 주소
    username: myuser                          # MySQL DB 접속 ID
    password: mypassword                      # MySQL DB 접속 PW

  # 페이지 설정
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 2000

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create  # DB 초기화 전략 (none, create, create-drop, update, validate)
    open-in-view: false  # Disable open-in-view to avoid performance issues
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL 방언으로 변경
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력

  # Cache 설정
  cache:
    type: redis

  # Redis 설정
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org:
      hibernate:
        SQL: OFF
        type:
          descriptor:
            sql:
              BasicBinder: OFF
    springframework:
      jdbc:
        core:
          JdbcTemplate: OFF
          StatementCreatorUtils: OFF
      orm:
        jpa: OFF
      transaction: OFF
      data:
        jpa:
          repository:
            query: OFF
          support:
            SimpleJpaRepository: OFF
      orm.jpa.vendor.HibernateJpaDialect: OFF